export const LOADING = "LOADING";
export const POST_ADMINREGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const ERROR = "ERROR";
export const GET_ALLUSERDATA="GET_ALLUSERDATA"
export const POST_ADMINLOGIN_SUCCESS="POST_LOGIN_SUCCESS";

export const GET_ALLPRODUCTDATA="GET_ALLPRODUCTDATA"

export const ADD_PRODUCT="ADD_PRODUCT"

export const UPDATE_PRODUCT="UPDATE_PRODUCT"

export const DELETE_PRODUCT="DELETE_PRODUCT"