


export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const REMOVE_DATA_FROM_CART = 'REMOVE_DATA_FROM_CART';
export const UPDATE_CART_PRICE = 'UPDATE_CART_PRICE';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';