export const POST_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS = "GETREGISTER_SUCCESS";
export const POST_REGISTER_ERROR = "GET_REGISTER_ERROR";

export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS";